# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:7

before_script:
  - echo 'registry=http://server.fluxgate.de:4873/' >> ~/.npmrc
  - echo '//server.fluxgate.de:4873/:_authToken="PeTF/FIpWZ/96ffjQ/5lbBVfa8zj0HREo4YIU26Sgx0="' >> ~/.npmrc
  - npm install gulp -g
  - npm install
 

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - lint
  - build

lintJob:
  stage: lint
  script: gulp tslint

buildJob:
  stage: build
  script: gulp publish -f